#3
Kalinka555/ToyShop pull request #5
Opened 2021-03-02 16:10 UTC by Kalinka555

2021-03-02 17:53 UTC, friendlyted requested changes, later dismissed
устранить замечания

2021-03-02 17:53 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +
убрать пустые строки

2021-03-02 17:53 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +        final Path PATH = Path.of("C:\\Users\\Alina\\IdeaProjects\\ToyShop\\src\\main\\resources\\ProductRegister(Toys).txt");
литералы вынести в константу (в класс)

2021-03-02 17:53 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            System.out.println("Usage:\n" +
вынести текст в константу

2021-03-02 17:53 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +                        "  java -jar ToyShop.jar [command] [options]\n" +
Два раза один и тот же текст, фуфуфу, используй переменную

2021-03-02 17:53 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            if (args[0].equals("list-products")) {
в константу

2021-03-02 17:53 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            } else if (args[0].equals("/?") || arg.equals("-?") || args.equals("-h") || arg.equals("--help") || arg.equals("?")) {
каждый литерал в константу

2021-03-02 17:53 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            if (args[0].equals("list-products")) {
только что объявила переменную arg, но тут же повторно обращаешься args[0]

2021-03-02 17:53 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            } else System.out.println("Welcome to our online shop");
welcome тоже в константу

2021-03-02 20:17 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +        final Path PATH = Path.of("C:\\Users\\Alina\\IdeaProjects\\ToyShop\\src\\main\\resources\\ProductRegister(Toys).txt");
Все литералы или только выделенный вынести в константу в класс?

2021-03-02 20:19 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            System.out.println("Usage:\n" +
Какой текст 15 строку, вынести в константу? я не могу их вместе запихнуть, тут переменная и условие и еще и метод

2021-03-02 20:31 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            if (args[0].equals("list-products")) {
что здесь выносить в константу? "list-products"? как же его назвать тогда? можно также оставить?

2021-03-02 20:32 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            if (args[0].equals("list-products")) {
это ключевое слово, я даже не могу назвать так переменную, потому что там тире только нижнее

2021-03-02 20:37 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            } else if (args[0].equals("/?") || arg.equals("-?") || args.equals("-h") || arg.equals("--help") || arg.equals("?")) {
каждый литерал? как я могу назвать каждый из них? Пять раз ?
                                final String слешсВопросом = "/?";
                                final String тиресВопросом = "/?"; и т.д. , я не пойму

2021-03-02 20:42 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +        final Path PATH = Path.of("C:\\Users\\Alina\\IdeaProjects\\ToyShop\\src\\main\\resources\\ProductRegister(Toys).txt");
Если я выношу в класс все переменные в методе требуют создать поле и переменные в классе  переименовываются в private static ... например private static Charset CHARSET = StandardCharsets.UTF_8;
final при этом удаляется, оставить так или все таки добавляю final , если это константа, то нужно де, верно?

2021-03-02 20:47 UTC, friendlyted requested changes

2021-03-02 20:47 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +        final Path PATH = Path.of("C:\\Users\\Alina\\IdeaProjects\\ToyShop\\src\\main\\resources\\ProductRegister(Toys).txt");
Здесь речь про весь путь файла из 13 строки

2021-03-02 20:47 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            System.out.println("Usage:\n" +
Смотреть надо на последнюю строку в комментарии. Это текст, который выводится как сообщение (строка 18 и ниже).

2021-03-02 20:47 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            if (args[0].equals("list-products")) {
Можно все переменные для команд начинать общим префиксом, например, COMMAND_LIST_PRODUCTS, COMMAND_HELP, COMMAND_H, COMMAND_QUESTION, COMMAND_QUESTION_MINUS, COMMAND_QUESTION_SLASH

2021-03-02 20:47 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            } else if (args[0].equals("/?") || arg.equals("-?") || args.equals("-h") || arg.equals("--help") || arg.equals("?")) {
см. комментарий выше, да, для каждого отдельная переменная

2021-03-02 20:58 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +        final Path PATH = Path.of("C:\\Users\\Alina\\IdeaProjects\\ToyShop\\src\\main\\resources\\ProductRegister(Toys).txt");
Ответь, пожалуйста, на этот тоже вопрос

2021-03-02 20:59 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +                        "  java -jar ToyShop.jar [command] [options]\n" +
Спасибо ))) принято )))
фу фу фу )))

2021-03-02 21:06 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +        final Path PATH = Path.of("C:\\Users\\Alina\\IdeaProjects\\ToyShop\\src\\main\\resources\\ProductRegister(Toys).txt");
У меня final не удалился, не могу прокомментировать

2021-03-03 18:45 UTC, friendlyted approved these changes

2021-03-03 18:46 UTC, merged