#6 Application with methods
Kalinka555/ToyShop pull request #8
Opened 2021-03-08 10:09 UTC by Kalinka555

#6 Application with methods

2021-03-08 10:47 UTC, friendlyted requested changes
Помнишь, мы договаривались, что print делается не внутри метода, а печатается то, что метод вернул? Только не сам метод должен печатать.

2021-03-08 10:59 UTC, Kalinka555 commented
А, а я решила, что надо вообще все спрятать ), ок, исправлю

2021-03-08 13:52 UTC, friendlyted requested changes

2021-03-08 13:52 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +     * метод для выявления буквенного ввода в параметры
Нет, метод, конечно, используется для этого. А если он будет в 10 местах использоваться, ты их тоже здесь перечислишь? Метод - для проверки, что в строке присутствую только цифры.

2021-03-08 13:52 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            e.printStackTrace();
Тут верни текст, что не удалось получить реестр товаров :(

Пользователю trace не очень полезен

2021-03-08 13:52 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +        return !input.matches("\\d+");
метод называется isNumeric, а возвращает по сути ответ на вопрос isNotNumeric...

2021-03-08 13:52 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            System.out.println(usageText(args));
ну, это работает как я просил, но все же сделай через переменную :)

2021-03-08 13:52 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +        return !input.matches("\\d+");
кстати, метод-то работает не совсем как хотелось :) Скорее всего, надо написать такой шаблон: `^\\d+$`

2021-03-08 13:55 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            System.out.println(usageText(args));
Я не понимаю что сделать через переменную

2021-03-08 14:33 UTC, alima-t commented on src/main/java/pro/kalinka/toyshop/Application.java
> +            System.out.println(usageText(args));
USAGE_TEXT - это было переменной, ты же хотел все в методы убрать, нет?

2021-03-08 15:55 UTC, friendlyted requested changes

2021-03-08 15:55 UTC, friendlyted commented on src/main/java/pro/kalinka/toyshop/Application.java
> +                return PARAMETERS_NOT_FILLED;
Давай мы этот try-catch запомним, чтобы когда-нибудь посмотреть на него)
А сейчас убери его и оставь просто return.

2021-03-08 15:58 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +                return PARAMETERS_NOT_FILLED;
Не получается  просто return

2021-03-08 15:59 UTC, Kalinka555 commented on src/main/java/pro/kalinka/toyshop/Application.java
> +                return PARAMETERS_NOT_FILLED;
Missing return value

2021-03-09 06:22 UTC, friendlyted approved these changes

2021-03-09 06:23 UTC, merged